# Generated by Django 2.0.1 on 2018-01-18 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Steam',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('steam_link', models.CharField(max_length=44)),
                ('discount', models.CharField(max_length=5)),
                ('price', models.CharField(max_length=10)),
                ('rating', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Steam_g2a',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(default='0', max_length=10)),
                ('g2a_link', models.CharField(default='', max_length=100)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listapp.Steam')),
            ],
        ),
    ]
