# Generated by Django 2.0.1 on 2018-03-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='humbleg2a',
            name='margin_num',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=20),
        ),
        migrations.AddField(
            model_name='humbleg2a',
            name='margin_percent',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=5),
        ),
    ]
