# Generated by Django 2.0.1 on 2018-03-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listapp', '0002_auto_20180309_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humbleg2a',
            name='margin_num',
            field=models.DecimalField(decimal_places=2, default='-100.00', max_digits=20),
        ),
        migrations.AlterField(
            model_name='humbleg2a',
            name='margin_percent',
            field=models.DecimalField(decimal_places=2, default='-100.00', max_digits=5),
        ),
    ]
